#!/usr/bin/python3
# Deletes the specified line in the specified table in the specified database.
# Edit history: CK created 20170810.

import sys
import subprocess
from getpass import getpass

if len(sys.argv)-1 != 3:
    print('USAGE: ./delete_line <database_name> <table_name> "comma_separated_line_to_be_deleted"')
    print('NOTE: the line to be deleted must be comma separated.')
    exit()

db = sys.argv[1]
table = sys.argv[2]
del_line = sys.argv[3]
del_line += '\n'

cwd = str(subprocess.check_output("pwd"))
filename = cwd[2:-3] + '/' + db + '/' + table + '.sdb'

dbkeyfilename = cwd[2:-3] + '/' + db + '/dbkey.txt'
ps = open(dbkeyfilename,'r')
for line in ps:
    dbkey = line.strip('\n')
    break

inkey = getpass('Enter the database key: ')
if inkey != dbkey:
    print('Incorrect database key.')
    exit()

towrite = []
f = open(filename,'r')
for line in f:
    towrite.append(line)

g = open(filename,'w')
written = []
for line in towrite:
    if line != del_line:
        written.append(line)
        g.write(line)

if len(written) < len(towrite):
    exit_status = 'Line "%s" successfully deleted from table %s/%s.'%(del_line[:-2],db,table)
    print(exit_status)
else:
    print('File unaltered.')


