#!/bin/bash
# Makes a simple database.
# Edit history: CK created 20170807.

echo -e "Hello, thank you for choosing snapdb! Let's make a database."
read -p "What do you want your database to be called? " db_name

while true; do
    read -p "Did you enter the correct name? (y/n) " yn
    case $yn in
        [Yy]* ) if [ -e "$db_name" ]; then echo "Database $db_name already exists. Remove it first using remove_db before creating a new one with the same name."; exit; fi; break;;
        [Nn]* ) read -p "What do you want your database to be called? " db_name;;
        * ) echo "Please answer y/n. ";;
    esac
done

echo "Now we need to create a database key to secure your data. Please type in a database key at the prompt."
echo -n "Database key: "
read -s password
echo

echo -n "Verify database key: "
read -s verify_password
echo
if [ "$password" == "$verify_password" ]; then
    mkdir -p "$db_name"
    chmod 700 "$db_name"
    echo "$password" > "$db_name"/dbkey.txt
    chmod 600 "$db_name"/dbkey.txt
else
    echo "Database keys did not match. Please try again."
    exit
fi

echo "Your database has been created!"
read -p "What would you like the description for your database to be? `echo $'\n> '`" db_descrip

echo "$db_descrip" > "$db_name"/description.txt

echo "Congratulations! Your database $db_name has been successfully created. To add tables to your database, use ./add_table $db_name. Happy logging!"
